# Enables support for Cross-Origin Request Sharing for added security
enableCORS = false

[browser]
#Internet address of the server that the browser should connect to
#default: localhost
serverAddress = "0.0.0.0"

# Whether to send usage statistics to Streamlit.
# Default: true
gatherUsageStats = true

# Port that the browser should use to connect to the server when in liveSave mode.
# Default: whatever value is set in server.port.
serverPort = 80